version: '2'
services:

  jenkins:
    image: jenkins
    ports:
     - "9001:8080"
     - "50000:50000"
    volumes:
     - /var/jenkins_home

  nexus:
    image: sonatype/nexus
    ports:
     - "8081:8081"
    volumes:
     - /sonatype-work

  postgres:
    image: postgres
    volumes:
     - /var/lib/postgressql/data
    environment:
     - POSTGRES_USER=sonar
     - POSTGRES_PASSWORD=sonar
     - POSTGRES_DB=sonar

  sonarqube:
    image: sonarqube
    links:
     - postgres
    ports:
     - "9000:9000"
     - "9092:9092"
    volumes:
     - /opt/sonarqube
    environment:
     - SONARQUBE_JDBC_USERNAME=sonar
     - SONARQUBE_JDBC_PASSWORD=sonar
     - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres/sonar
